import About from '@/Components/About'
import Experience from '@/Components/Experience'
import Header from '@/Components/Header'
import Hero from '@/Components/Hero'
import Skills from '@/Components/Skills'
import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div className='bg-cyan-900 text-white h-screen snap-y snap-mandatory overflow-scroll z-0 '>
      <Head>
        <title>Abhishek || Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header  */}
      <Header />
      {/* Hero  */}
      <section id='hero' className='snap-start'>

      <Hero />
      </section>
     {/* About  */} 
     <section id='about' className='snap-center'>

     <About />
     </section>
     {/* Experience  */}
     <section id='experience' className='snap-center'>

     <Experience />
     </section>
     {/* Skills  */}
<section id='skills'>
  <Skills />
</section>
     {/* Projects  */}
     {/* Contact Me  */}
    </div>
  )
}
