import About from '@/Components/About'
import ContactMe from '@/Components/ContactMe'
import Experience from '@/Components/Experience'
import Header from '@/Components/Header'
import Hero from '@/Components/Hero'
import Project from '@/Components/Project'
import Skills from '@/Components/Skills'
import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <div className='bg-cyan-900 text-white h-screen snap-y snap-mandatory overflow-x-hidden overflow-y-scroll z-0 '>
      <Head>
        <title>Abhishek || Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header  */}
      <Header />
      {/* Hero  */}
      <section id='hero' className='snap-start'>

      <Hero />
      </section>
     {/* About  */} 
     <section id='about' className='snap-center'>

     <About />
     </section>
     {/* Experience  */}
     <section id='experience' className='snap-center'>

     <Experience />
     </section>
     {/* Skills  */}
<section id='skills' className='snap-start'>
  <Skills />
</section>
     {/* Projects  */}
     <section id='project' className='snap-start'>
      <Project />
     </section>
     {/* Contact Me  */}
     <section id='contact' className='snap-start'>
      <ContactMe />
     </section>
     <Link href="#hero">
      <footer className='sticky bottom-5 w-full cursor-pointer'>
<div className='flex items-center justify-center'>

      <img className='w-10 h-10 rounded-full grayscale hover:grayscale-0 cursor-pointer' src='https://pbs.twimg.com/profile_images/1634229831000027136/SGHVSziK_400x400.jpg'/>
</div>
      </footer>
     </Link>
    </div>
  )
}
