import Header from '@/Components/Header'
import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <>
      <Head>
        <title>Abhishek || Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header  */}
      <Header />
      {/* Hero  */}
     {/* About  */}
     {/* Experience  */}
     {/* Skills  */}
     {/* Projects  */}
     {/* Contact Me  */}
    </>
  )
}
